blank_issues_enabled: false
contact_links:
  - name: Feature
    url: https://github.community/
    about: Please ask and answer questions here.
  - name: Bug
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
